#!/bin/bash

lsres=$(ls | grep "manage.py")
while [ -z "$lsres" ]; do
    curr_dir=$(pwd)
    if [ "$curr_dir" == "$HOME" ]
    then
        exit
    fi
    cd ..
    lsres=$(ls | grep "manage.py")
done

python3 manage.py $1
